#!/bin/sh
# getsolar - extracts data from a Sunspec compliant AC Inverter

# you need to make the PIDFILE dir and ensure it has the right permissions
PIDFILE="/tmp/getsolar.pid"
export PIDFILE
PYTHON="/home/steve/projects/getsolar/.venv/bin/python"
RUNFILE="/usr/local/bin/getsolar.py"
DEVICE_ADDRESS="solaredge.smcallister.org"
#DEVICE_ADDRESS="localhost"
DEBUG=


start()
{
 if [ -f "$PIDFILE" ] ; then
    /bin/ps `cat $PIDFILE` >/dev/null
    if [ $? ] ; then
        echo "Cleaning up old PID file"
        /bin/rm $PIDFILE
    else
        echo "$RUNFILE is already running"
        exit 1
    fi
 fi
 if [ $DEBUG ] ; then
   $PYTHON $RUNFILE -D -i $DEVICE_ADDRESS
 else
   $PYTHON $RUNFILE -i $DEVICE_ADDRESS
 fi
 exit $?
    
}

stop()
{
 [ -f "$PIDFILE" ] && kill `cat "$PIDFILE"` && /bin/rm "$PIDFILE"
}

restart()
{
 stop
 sleep 1
 start
}

case "$1" in
 "start")
  start
 ;;
 "stop")
  stop
 ;;
 "restart")
  restart
 ;;
 *)
  "$@"
 ;;
esac

